export const productos = [
	{
		id: 1,
		nombre: 'Hamburguesa Clásica',
		precio: 5.99,
		ingredientes: ['pan', 'carne de res', 'queso', 'lechuga', 'tomate', 'mayonesa'],
		descripcion: 'Hamburguesa clásica con carne de res, queso cheddar, lechuga fresca y tomate.',
	},
	{
		id: 2,
		nombre: 'Hamburguesa BBQ',
		precio: 6.99,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'cebolla caramelizada', 'salsa barbacoa', 'lechuga'],
		descripcion: 'Hamburguesa con salsa barbacoa, cebolla caramelizada y queso cheddar.',
	},
	{
		id: 3,
		nombre: 'Hamburguesa Veggie',
		precio: 5.49,
		ingredientes: ['pan', 'hamburguesa de vegetales', 'lechuga', 'tomate', 'mayonesa vegana'],
		descripcion: 'Una opción sin carne con hamburguesa de vegetales, ideal para veganos.',
	},
	{
		id: 4,
		nombre: 'Hamburguesa Deluxe',
		precio: 8.49,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'bacon', 'huevo frito', 'lechuga', 'tomate'],
		descripcion: 'Hamburguesa de lujo con bacon crujiente, huevo frito y queso cheddar.',
	},
	{
		id: 5,
		nombre: 'Hamburguesa Hawaiana',
		precio: 7.99,
		ingredientes: ['pan', 'carne de res', 'queso suizo', 'piña', 'jamón', 'mayonesa'],
		descripcion: 'Hamburguesa con piña a la parrilla y jamón, todo en un pan suave.',
	},
	{
		id: 6,
		nombre: 'Hamburguesa Picante',
		precio: 6.49,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'jalapeños', 'salsa picante'],
		descripcion: 'Hamburguesa con un toque picante gracias a los jalapeños y la salsa picante.',
	},
	{
		id: 7,
		nombre: 'Hamburguesa Tex-Mex',
		precio: 7.49,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'guacamole', 'cebolla morada', 'lechuga'],
		descripcion: 'Hamburguesa con guacamole, cebolla morada y un toque de queso cheddar.',
	},
	{
		id: 8,
		nombre: 'Hamburguesa Bacon & Cheese',
		precio: 6.99,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'bacon', 'lechuga', 'mayonesa'],
		descripcion: 'Hamburguesa con queso cheddar fundido y crujiente bacon.',
	},
	{
		id: 9,
		nombre: 'Hamburguesa Mushroom',
		precio: 7.99,
		ingredientes: ['pan', 'carne de res', 'queso suizo', 'setas', 'salsa de mostaza'],
		descripcion: 'Hamburguesa con setas salteadas y queso suizo derretido.',
	},
	{
		id: 10,
		nombre: 'Hamburguesa Mexicana',
		precio: 8.99,
		ingredientes: ['pan', 'carne de res', 'queso cheddar', 'guacamole', 'salsa de chipotle'],
		descripcion: 'Hamburguesa con guacamole, salsa chipotle y queso cheddar.',
	},
	{
		id: 11,
		nombre: 'Burrito Clásico',
		precio: 5.99,
		ingredientes: ['tortilla', 'carne de res', 'arroz', 'frijoles', 'lechuga', 'queso cheddar', 'salsa'],
		descripcion: 'Burrito clásico con carne de res, arroz y frijoles.',
	},
	{
		id: 12,
		nombre: 'Burrito Vegetariano',
		precio: 5.49,
		ingredientes: ['tortilla', 'arroz', 'frijoles', 'aguacate', 'lechuga', 'tomate', 'salsa'],
		descripcion: 'Burrito vegetariano con frijoles, arroz, aguacate y salsa fresca.',
	},
	{
		id: 13,
		nombre: 'Burrito Picante',
		precio: 6.49,
		ingredientes: ['tortilla', 'carne de pollo', 'arroz', 'jalapeños', 'salsa picante', 'queso cheddar'],
		descripcion: 'Burrito con pollo, jalapeños y salsa picante.',
	},
	{
		id: 14,
		nombre: 'Burrito BBQ',
		precio: 7.49,
		ingredientes: ['tortilla', 'carne de res', 'salsa barbacoa', 'arroz', 'queso', 'tomate'],
		descripcion: 'Burrito con carne de res, salsa barbacoa y arroz.',
	},
	{
		id: 15,
		nombre: 'Burrito Supreme',
		precio: 8.99,
		ingredientes: ['tortilla', 'carne de res', 'arroz', 'frijoles negros', 'guacamole', 'queso cheddar', 'sour cream'],
		descripcion: 'Burrito supreme con carne, guacamole, frijoles negros y sour cream.',
	},
	{
		id: 16,
		nombre: 'Burrito Taco',
		precio: 6.99,
		ingredientes: ['tortilla', 'carne de res', 'lechuga', 'tomate', 'queso cheddar', 'salsa'],
		descripcion: 'Burrito inspirado en los tacos, con carne de res, lechuga y salsa.',
	},
	{
		id: 17,
		nombre: 'Burrito de Pollo',
		precio: 5.99,
		ingredientes: ['tortilla', 'pollo', 'arroz', 'lechuga', 'salsa', 'queso'],
		descripcion: 'Burrito con pollo tierno, arroz y salsa fresca.',
	},
	{
		id: 18,
		nombre: 'Burrito del Mar',
		precio: 9.49,
		ingredientes: ['tortilla', 'mariscos', 'arroz', 'guacamole', 'lechuga', 'salsa de chipotle'],
		descripcion: 'Burrito con mariscos frescos, guacamole y salsa de chipotle.',
	},
	{
		id: 19,
		nombre: 'Burrito Loco',
		precio: 8.49,
		ingredientes: ['tortilla', 'carne de res', 'jalapeños', 'queso', 'tomate', 'lechuga'],
		descripcion: 'Burrito loco con carne, jalapeños y mucho queso.',
	},
	{
		id: 20,
		nombre: 'Papas Fritas Clásicas',
		precio: 2.99,
		ingredientes: ['papas', 'aceite', 'sal'],
		descripcion: 'Papas fritas crujientes, saladas al gusto.',
	},
	{
		id: 21,
		nombre: 'Papas Fritas con Queso',
		precio: 3.99,
		ingredientes: ['papas', 'aceite', 'queso cheddar', 'salsa de queso'],
		descripcion: 'Papas fritas cubiertas con queso cheddar fundido.',
	},
	{
		id: 22,
		nombre: 'Papas Fritas con Bacon',
		precio: 4.49,
		ingredientes: ['papas', 'aceite', 'bacon', 'queso cheddar', 'salsa BBQ'],
		descripcion: 'Papas fritas con bacon crujiente y salsa BBQ.',
	},
	{
		id: 23,
		nombre: 'Papas Fritas Picantes',
		precio: 3.49,
		ingredientes: ['papas', 'aceite', 'jalapeños', 'salsa picante'],
		descripcion: 'Papas fritas con un toque de jalapeños y salsa picante.',
	},
	{
		id: 24,
		nombre: 'Papas Fritas Deluxe',
		precio: 5.49,
		ingredientes: ['papas', 'aceite', 'queso cheddar', 'bacon', 'sour cream'],
		descripcion: 'Papas fritas deluxe con queso, bacon y sour cream.',
	},
	{
		id: 25,
		nombre: 'Bebida Cola',
		precio: 1.99,
		ingredientes: ['agua carbonatada', 'azúcar', 'colorante', 'saborizante'],
		descripcion: 'Bebida cola refrescante y deliciosa.',
	},
	{
		id: 26,
		nombre: 'Bebida Limón',
		precio: 1.79,
		ingredientes: ['agua', 'jugo de limón', 'azúcar'],
		descripcion: 'Bebida refrescante con jugo de limón natural.',
	},
	{
		id: 27,
		nombre: 'Bebida Naranja',
		precio: 1.89,
		ingredientes: ['agua', 'jugo de naranja', 'azúcar'],
		descripcion: 'Bebida refrescante de jugo de naranja natural.',
	},
	{
		id: 28,
		nombre: 'Bebida Energética',
		precio: 2.49,
		ingredientes: ['agua', 'azúcar', 'cafeína', 'saborizantes'],
		descripcion: 'Bebida energética con un toque refrescante.',
	},
	{
		id: 29,
		nombre: 'Bebida Té Helado',
		precio: 2.19,
		ingredientes: ['agua', 'té', 'azúcar', 'saborizantes'],
		descripcion: 'Té helado refrescante con un toque dulce.',
	},
	{
		id: 30,
		nombre: 'Bebida Fresa',
		precio: 2.29,
		ingredientes: ['agua', 'saborizante de fresa', 'azúcar'],
		descripcion: 'Bebida fresca con sabor a fresa natural.',
	},
	{
		id: 31,
		nombre: 'Pepsi',
		precio: 1.4,
		ingredientes: ['agua carbonatada', 'azúcar', 'colorante caramelo E150d', 'ácido fosfórico', 'aroma natural', 'cafeína'],
		descripcion: 'Refresco carbonatado de cola con un sabor único.',
	},
	{
		id: 32,
		nombre: 'Agua mineral Evian',
		precio: 2.0,
		ingredientes: ['agua mineral natural'],
		descripcion: 'Agua mineral natural proveniente de los Alpes franceses, rica en minerales.',
	},
]
