export const productos = [
	{
		id: 1,
		nombre: 'Hamburguesa Clásica',
		precio: 90,
		ingredientes: ['Pan', 'Carne de res', 'Queso', 'Lechuga', 'Tomate', 'Mayonesa'],
		descripcion: 'Hamburguesa clásica con carne de res, queso cheddar, lechuga fresca y tomate.',
	},
	{
		id: 2,
		nombre: 'Hamburguesa BBQ',
		precio: 110,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Cebolla caramelizada', 'Salsa barbacoa', 'Lechuga'],
		descripcion: 'Hamburguesa con salsa barbacoa, cebolla caramelizada y queso cheddar.',
	},
	{
		id: 3,
		nombre: 'Hamburguesa Veggie',
		precio: 120,
		ingredientes: ['Pan', 'Hamburguesa de vegetales', 'Lechuga', 'Tomate', 'Mayonesa vegana'],
		descripcion: 'Una opción sin carne con hamburguesa de vegetales, ideal para veganos.',
	},
	{
		id: 4,
		nombre: 'Hamburguesa Deluxe',
		precio: 150,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Bacon', 'Huevo frito', 'Lechuga', 'Tomate'],
		descripcion: 'Hamburguesa de lujo con bacon crujiente, huevo frito y queso cheddar.',
	},
	{
		id: 5,
		nombre: 'Hamburguesa Hawaiana',
		precio: 170,
		ingredientes: ['Pan', 'Carne de res', 'Queso suizo', 'Piña', 'Jamón', 'Mayonesa'],
		descripcion: 'Hamburguesa con piña a la parrilla y jamón, todo en un pan suave.',
	},
	{
		id: 6,
		nombre: 'Hamburguesa Picante',
		precio: 130,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Jalapeños', 'Salsa picante'],
		descripcion: 'Hamburguesa con un toque picante gracias a los jalapeños y la salsa picante.',
	},
	{
		id: 7,
		nombre: 'Hamburguesa Tex-Mex',
		precio: 120,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Guacamole', 'Cebolla morada', 'Lechuga'],
		descripcion: 'Hamburguesa con guacamole, cebolla morada y un toque de queso cheddar.',
	},
	{
		id: 8,
		nombre: 'Hamburguesa Bacon & Cheese',
		precio: 190,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Bacon', 'Lechuga', 'Mayonesa'],
		descripcion: 'Hamburguesa con queso cheddar fundido y crujiente bacon.',
	},
	{
		id: 9,
		nombre: 'Hamburguesa Mushroom',
		precio: 145,
		ingredientes: ['Pan', 'Carne de res', 'Queso suizo', 'Setas', 'Salsa de mostaza'],
		descripcion: 'Hamburguesa con setas salteadas y queso suizo derretido.',
	},
	{
		id: 10,
		nombre: 'Hamburguesa Mexicana',
		precio: 155,
		ingredientes: ['Pan', 'Carne de res', 'Queso cheddar', 'Guacamole', 'Salsa de chipotle'],
		descripcion: 'Hamburguesa con guacamole, salsa chipotle y queso cheddar.',
	},
	{
		id: 11,
		nombre: 'Burrito Clásico',
		precio: 50,
		ingredientes: ['Tortilla', 'Carne de res', 'Arroz', 'Frijoles', 'Lechuga', 'Queso cheddar', 'Salsa'],
		descripcion: 'Burrito clásico con carne de res, arroz y frijoles.',
	},
	{
		id: 12,
		nombre: 'Burrito Vegetariano',
		precio: 60,
		ingredientes: ['Tortilla', 'Arroz', 'Frijoles', 'Aguacate', 'Lechuga', 'Tomate', 'Salsa'],
		descripcion: 'Burrito vegetariano con frijoles, arroz, aguacate y salsa fresca.',
	},
	{
		id: 13,
		nombre: 'Burrito Picante',
		precio: 55,
		ingredientes: ['Tortilla', 'Carne de pollo', 'Arroz', 'Jalapeños', 'Salsa picante', 'Queso cheddar'],
		descripcion: 'Burrito con pollo, jalapeños y salsa picante.',
	},
	{
		id: 14,
		nombre: 'Burrito BBQ',
		precio: 70,
		ingredientes: ['Tortilla', 'Carne de res', 'Salsa barbacoa', 'Arroz', 'Queso', 'Tomate'],
		descripcion: 'Burrito con carne de res, salsa barbacoa y arroz.',
	},
	{
		id: 15,
		nombre: 'Burrito Supreme',
		precio: 80,
		ingredientes: ['Tortilla', 'Carne de res', 'Arroz', 'Frijoles negros', 'Guacamole', 'Queso cheddar', 'Sour cream'],
		descripcion: 'Burrito supreme con carne, guacamole, frijoles negros y sour cream.',
	},
	{
		id: 16,
		nombre: 'Burrito Taco',
		precio: 65,
		ingredientes: ['Tortilla', 'Carne de res', 'Lechuga', 'Tomate', 'Queso cheddar', 'Salsa'],
		descripcion: 'Burrito inspirado en los tacos, con carne de res, lechuga y salsa.',
	},
	{
		id: 17,
		nombre: 'Burrito de Pollo',
		precio: 65,
		ingredientes: ['Tortilla', 'Pollo', 'Arroz', 'Lechuga', 'Salsa', 'Queso'],
		descripcion: 'Burrito con pollo tierno, arroz y salsa fresca.',
	},
	{
		id: 18,
		nombre: 'Burrito del Mar',
		precio: 100,
		ingredientes: ['Tortilla', 'Mariscos', 'Arroz', 'Guacamole', 'Lechuga', 'Salsa de chipotle'],
		descripcion: 'Burrito con mariscos frescos, guacamole y salsa de chipotle.',
	},
	{
		id: 19,
		nombre: 'Burrito Loco',
		precio: 85,
		ingredientes: ['Tortilla', 'Carne de res', 'Jalapeños', 'Queso', 'Tomate', 'Lechuga'],
		descripcion: 'Burrito loco con carne, jalapeños y mucho queso.',
	},
	{
		id: 20,
		nombre: 'Papas Fritas Clásicas',
		precio: 50,
		ingredientes: ['Papas', 'Aceite', 'Sal'],
		descripcion: 'Papas fritas crujientes, saladas al gusto.',
	},
	{
		id: 21,
		nombre: 'Papas Fritas con Queso',
		precio: 60,
		ingredientes: ['Papas', 'Aceite', 'Queso cheddar', 'Salsa de queso'],
		descripcion: 'Papas fritas cubiertas con queso cheddar fundido.',
	},
	{
		id: 22,
		nombre: 'Papas Fritas con Bacon',
		precio: 65,
		ingredientes: ['Papas', 'Aceite', 'Bacon', 'Queso cheddar', 'Salsa BBQ'],
		descripcion: 'Papas fritas con bacon crujiente y salsa BBQ.',
	},
	{
		id: 23,
		nombre: 'Papas Fritas Picantes',
		precio: 60,
		ingredientes: ['Papas', 'Aceite', 'Jalapeños', 'Salsa picante'],
		descripcion: 'Papas fritas con un toque de jalapeños y salsa picante.',
	},
	{
		id: 24,
		nombre: 'Papas Fritas Deluxe',
		precio: 70,
		ingredientes: ['Papas', 'Aceite', 'Queso cheddar', 'Bacon', 'Sour cream'],
		descripcion: 'Papas fritas deluxe con queso, bacon y sour cream.',
	},
	{
		id: 25,
		nombre: 'Bebida Cola',
		precio: 25,
		ingredientes: ['Agua carbonatada', 'Azúcar', 'Colorante', 'Saborizante'],
		descripcion: 'Bebida cola refrescante y deliciosa.',
	},
	{
		id: 26,
		nombre: 'Bebida Limón',
		precio: 25,
		ingredientes: ['Agua', 'Jugo de limón', 'Azúcar'],
		descripcion: 'Bebida refrescante con jugo de limón natural.',
	},
	{
		id: 27,
		nombre: 'Bebida Naranja',
		precio: 30,
		ingredientes: ['Agua', 'Jugo de naranja', 'Azúcar'],
		descripcion: 'Bebida refrescante de jugo de naranja natural.',
	},
	{
		id: 28,
		nombre: 'Bebida Energética',
		precio: 20,
		ingredientes: ['Agua', 'Azúcar', 'Cafeína', 'Saborizantes'],
		descripcion: 'Bebida energética con un toque refrescante.',
	},
	{
		id: 29,
		nombre: 'Bebida Té Helado',
		precio: 30,
		ingredientes: ['Agua', 'Té', 'Azúcar', 'Saborizantes'],
		descripcion: 'Té helado refrescante con un toque dulce.',
	},
	{
		id: 30,
		nombre: 'Bebida Fresa',
		precio: 35,
		ingredientes: ['Agua', 'Saborizante de fresa', 'Azúcar'],
		descripcion: 'Bebida fresca con sabor a fresa natural.',
	},
	{
		id: 31,
		nombre: 'Pepsi',
		precio: 25,
		ingredientes: ['Agua carbonatada', 'Azúcar', 'Colorante caramelo E150d', 'Ácido fosfórico', 'Aroma natural', 'Cafeína'],
		descripcion: 'Refresco carbonatado de cola con un sabor único.',
	},
	{
		id: 32,
		nombre: 'Agua mineral Evian',
		precio: 25,
		ingredientes: ['Agua mineral natural'],
		descripcion: 'Agua mineral natural proveniente de los Alpes franceses, rica en minerales.',
	},
]
